<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BootstrapIcons.AspNetCore" Version="1.13.0" />
    <PackageReference Include="taglib-sharp-netstandard2.0" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Trackify.Service\Trackify.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\ImagesAndSongs\Albums\" />
  </ItemGroup>

</Project>
